export const listComic = [
	{
		imgUrl: "./images/theFirstNightWithTheDuke.png",
		title: "The First Night With the Duke",
		author: "MSG/Teava",
		genre: "fantasy",
		info: "A handsome, selfish noble falls for a beautiful, kind commoner -- at least, that’s how the story’s supposed to go. When an average college student wakes up as Ripley, an extra in her favorite romance novel, she resolves to enjoy the luxuries of her character’s status while watching the novel's plot unfold from the sidelines. However, her plans are soon derailed when she finds herself in bed with no other than Duke Zeronis, the novel’s hero! Dodging the villainess’ schemes, the Duke’s advances, and her own feelings, can Ripley keep the story on track and survive beyond the first night?",
		like: 4000000,
		sub: 890000,
		rate: 9.67,
		weekday: ["mon"],
	},
	{
		imgUrl: "./images/toLoveYourEnemy.png",
		imgMulUrl: "./images/toLoveYourEnemy_mul.png",
		title: "To Love Your Enemy",
		author: "Jungyoon/Teageon",
		genre: "romance",
		info: "Having mastered the art of lying her way through life, Yeonhee Bae has vowed to leave her past behind and make a fresh start for herself by going to college at 24. But when she runs into someone who knows a secret from her past that could completely ruin her reputation, her hopes for a perfect life suddenly start to crumble. Amidst college gossip, crushes, and jealousy, can the two set aside their differences and embrace each other for who they really are?",
		like: 9000000,
		sub: 1600000,
		rate: 9.78,
		weekday: ["mon","thu"],
	},{
		imgUrl: "./images/towerOfGod.png",
		title: "Tower of God",
		author: "SIU",
		genre: "fantasy",
		info: "What do you desire? Money and wealth? Honor and pride? Authority and power? Revenge? Or something that transcends them all? Whatever you desire—it's here.",
		like: 41000000,
		sub: 2800000,
		rate: 9.86,
		weekday: ["mon"],
	},
	{
		imgUrl: "./images/everythingIsFine_mul.png",
		imgMulUrl: "./images/everythingIsFine_mul.png",
		title: "Everything is Fine",
		author: "Mike Birchall",
		genre: "horror",
		info: "Sam and Maggie are a normal couple, in a normal house, in a normal neighborhood. There is nothing strange about their heads, their neighbors or their sweet little dog. Everything is Fine.",
		like: 555000,
		sub: 318000,
		rate: 9.72,
		weekday: ["mon"],
	},
	{
		imgUrl: "./images/theFourOfThem.png",
		title: "The Four of Them",
		author: "Mai Hirschfeld",
		genre: "drama",
		info: "Getting crushed by your crush. Coming out to your parents. Learning that your sister is your biggest dating rival. High school sure does have its share of twists, turns and moments of high drama. To get through it all with your smile and sanity intact, you’re going to need some friends. Really good friends. Friends like Johnny, Mariel, Gaby and Martina who, one way or another, will find a way to get through their teenage years together.",
		like: 5600000,
		sub: 970000,
		rate: 9.58,
		weekday: ["mon"],
	},
	{
		imgUrl: "./images/myGiantNerdBoyfriend.png",
		title: "My Giant Nerd Boyfriend",
		author: "fishball",
		genre: "slice of life",
		info: `Having a boyfriend who's a full foot taller than you might seem adorable at first, but it usually just ends up causing a whole bunch of minor inconveniences. Follow Fishball as she navigates the Malaysian life with her 6'5" geeky boyfriend.`,
		like: 47000000,
		sub: 2100000,
		rate: 9.73,
		weekday: ["mon", "wed", "fri"],
	},
	{
		imgUrl: "./images/itsMine.png",
		title: "It's Mine",
		author: "LuckS",
		genre: "thriller",
		info: `There’s nothing that Yohan Do doesn’t know about his crush, Dajeong. Where she sits in class, works after school... and even where she lives. But unable to approach her, he watches her every move from afar and will do anything to protect her. Anything.`,
		like: 5500000,
		sub: 940000,
		rate: 9.73,
		weekday: ["mon", "thu"],
	},
	{
		imgUrl: "./images/dungeons&Artifacts.png",
		title: "Dungeons & Artifacts",
		author: "Zerowater / UMKY ",
		genre: "action",
		info: `A dungeon-guiding gig goes sideways for explorer Stetch Atelier when the prince who hired him tricks him into activating a fatal curse. But instead of staying dead, Stetch is resurrected by a sentient artifact that offers him a deal that may help him get his revenge. To hold up his end of the bargain, Stetch sets off on a long journey of raiding dungeons, slaying monsters, and making new enemies and friends along the way.`,
		like: 410000,
		sub: 320000,
		rate: 9.53,
		weekday: ["mon"],
	},
	{
		imgUrl: "./images/downToEarth.png",
		title: "Down To Earth",
		author: "Pookie Senpai",
		genre: "romance",
		info: `Kade lives his average life alone and undisturbed... until a cute alien girl crashes into his backyard! By opening up his home, will this other worldly girl inadvertently open up his heart?`,
		like: 8600000,
		sub: 1900000,
		rate: 9.82,
		weekday: ["tue"],
	},
	{
		imgUrl: "./images/boyfriends.png",
		title: "Boyfriends.",
		author: "refrainbow ",
		genre: "slice of life",
		info: `A comic about getting yourself a boyfriend... or multiple boyfriends! Four college students begin a polyamorous relationship and navigate the adventure that is their dating life!`,
		like: 4100000,
		sub: 932000,
		rate: 9.49,
		weekday: ["tue", "fri"],
	},
	{
		imgUrl: "./images/myDeepestSecret.png",
		title: "My Deepest Secret",
		author: "Hanza Art",
		genre: "thriller",
		info: `Having a handsome, kind and caring boyfriend like Elios means the world to Emma. Even a look at him makes her heart flutters. But little does she know about a secret lies deep in their relationship. What is the said secret?`,
		like: 11000000,
		sub: 2300000,
		rate: 9.71,
		weekday: ["tue"],
	},
	{
		imgUrl: "./images/theAdvancedPlayerOfTheTutorialTower.png",
		title: "The Advanced Player of the Tutorial Tower",
		author: "Bangguseok Gimssi / Omagam ...",
		genre: "action",
		info: `Having a handsome, kind and caring boyfriend like Elios means the world to Emma. Even a look at him makes her heart flutters. But little does she know about a secret lies deep in their relationship. What is the said secret?`,
		like: 1900000,
		sub: 850000,
		rate: 9.56,
		weekday: ["tue"],
	},
	{
		imgUrl: "./images/theMakeupRemover.png",
		title: "The Makeup Remove",
		author: "Lee Yone",
		genre: "romance",
		info: `After years of being told to focus on studying, Yeseul feels lost when she starts college and is suddenly expected to pay attention to makeup. When a chance encounter with brilliant makeup artist Yuseong leads to her taking part in a televised makeup competition, Yeseul begins to question the role that makeup and appearance play in society.`,
		like: 6500000,
		sub: 980000,
		rate: 9.71,
		weekday: ["tue", "fri"],
	},
	{
		imgUrl: "./images/acception.png",
		title: "Acception",
		author: "Colourbee",
		genre: "drama",
		info: `With his rainbow-colored hair and love of all things fashion, Arcus is anything BUT your average teenager. He’s an upbeat independent thinker, proud fashionista, and like the rest of us, is just looking for a few friends to call his own. Acception may be Arcus’ story – but it’s all OUR stories too - and it is for anyone who’s ever struggled to fit in, find love, or thought that High School was pretty much the worst thing ever invented.`,
		like: 8600000,
		sub: 690000,
		rate: 9.08,
		weekday: ["tue", "fri"],
	},
	{
		imgUrl: "./images/seasonsOfBloom.png",
		title: "Seasons of Blossom",
		author: "HONGDUCK / NEMONE",
		genre: "romance",
		info: `Oh, to be young and in love. Oh, to be wild and carefree. The springtime of life is intense, tumultuous, and at times, oh so confusing. Spring, summer, fall and winter -- love blossoms in all seasons.`,
		like: 1600000,
		sub: 480000,
		rate: 9.84,
		weekday: ["tue", "sat"],
	},
	{
		imgUrl: "./images/boyfriendOfTheDead.png",
		title: "Boyfriend of the Dead",
		author: "Ushio",
		genre: "comedy",
		info: `She’s a smart, independent young woman who’s kicking ass and struggling to make her way through the middle of the zombie apocalypse. Just her luck: one day she goes out searching for food and shelter and ends up finding a boyfriend instead. And, oh yeah, because modern love isn’t hard enough…he’s UNDEAD!`,
		like: 26000000,
		sub: 1900000,
		rate: 9.74,
		weekday: ["tue", "fri"],
	},
	{
		imgUrl: "./images/eleceed_mul.png",
		imgMulUrl: "./images/eleceed_mul.png",
		title: "Eleceed",
		author: "Jeho Son / ZHENA",
		genre: "action",
		info: `Jiwoo is a kind-hearted young man who harnesses the lightning quick reflexes of a cat to secretly make the world a better place – one saved little child or foster pet at a time. Kayden is a secret agent on the run, who finds himself stuck in the body of a…um…decidedly fat old fluffy cat. Together, armed with Jiwoo’s super powers and Kayden’s uber-smarts, they’re out to fight those forces who would let evil rule this world. That is, if they can stand each other long enough to get the job done.`,
		like: 8200000,
		sub: 820000,
		rate: 9.93,
		weekday: ["tue"],
	},
	{

		imgUrl: "./images/trueBeauty.png",
		title: "True Beauty",
		author: "Yaongyi",
		genre: "romance",
		info: `After binge-watching beauty videos online, a shy comic book fan masters the art of makeup and sees her social standing skyrocket as she becomes her school’s prettiest pretty girl overnight. But will her elite status be short-lived? How long can she keep her real self a secret? And what about that cute boy who knows her secret?`,
		like: 37000000,
		sub: 6200000,
		rate: 9.64,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/ageMatters.png",
		title: "Age Matters",
		author: "Enjelicious",
		genre: "romance",
		info: `She’s a hopeless romantic who’s turning 30 – and is not super happy about it. He’s a reclusive billionaire who’s hired her to be his assistant – and he’s not too happy about that either. Together they rewrite the rules of friendship, love, work and the BEST way to clean someone’s apartment.`,
		like: 23000000,
		sub: 3300000,
		rate: 9.80,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/omniscientReader.png",
		title: "Omniscient Reader",
		author: "sing N song / UMI ...",
		genre: "action",
		info: `Dokja was an average office worker whose sole interest was reading his favorite web novel 'Three Ways to Survive the Apocalypse.' But when the novel suddenly becomes reality, he is the only person who knows how the world will end. Armed with this realization, Dokja uses his understanding to change the course of the story, and the world, as he knows it.`,
		like: 6000000,
		sub: 1300000,
		rate: 9.90,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/phase.png",
		title: "Phase",
		author: "Jouki",
		genre: "romance",
		info: `Min is unique. Plagued by debts, misfortune and a troubled past her life has been anything but normal. When she has the opportunity to earn a great deal of money, 50 million dollars to be exact, she would be a fool to refuse. Despite the odd conditions she takes a chance with Shuu, the handsome, irritating billionare who can change her life. Can she keep her secrets close to her chest or will she ruin them both?`,
		like: 3300000,
		sub: 800000,
		rate: 9.60,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/loveMeKnot.png",
		title: "Love Me Knot",
		author: "Sophia",
		genre: "romance",
		info: `You'd think that being able to see the Red String of Fate would make finding your soulmate a lot easier. But for Avery, the blossoming romance​ around her only emphasizes her own string... with no one attached to the other end. Is Avery destined to live a loveless life, or can she tailor her own romance?`,
		like: 2900000,
		sub: 800000,
		rate: 9.39,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/swimmingLessonsForAMermaid.png",
		title: "Swimming Lessons for a Mermaid",
		author: "YONGCHAN",
		genre: "romance",
		info: `Choa is a mermaid who can't swim! Discouraged, she trades the ocean for a pair of human legs. But when the star of the high school swim team finds out her secret, he offers her the chance to prove her family wrong: free swimming lessons for a mermaid!`,
		like: 4200000,
		sub: 675000,
		rate: 9.74,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/infiniteLevelingMurim_mul.png",
		imgMulUrl: "./images/infiniteLevelingMurim_mul.png",
		title: "Infinite Leveling: Murim",
		author: "Jinwoo Kim / Gonbung",
		genre: "action",
		info: `Killed on the battlefield without glory to his name, Yuseong Dan receives an opportunity to grow stronger with a strange quest and level system. But each quest he’s forced to fight only seems to be getting harder and harder. Can he level up enough to avoid the same miserable ending and become the powerful hero he wishes to be?`,
		like: 100000,
		sub: 170000,
		rate: 9.48,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/thePrinceOfSouthland.png",
		title: "The Prince of Southland",
		author: "Chris Geroux",
		genre: "romance",
		info: `Donnie Ali's shiny reputation is soiled the night he kissed an android, for romantic relationships with droids are deemed too dangerous and forbidden. But after his press release, another potential scandal emerges when he saves Jensen, a man on the run from an unknown assailant. Now living under the same roof, and paparazzi on every corner, could this romance be even more disastrous than his first?`,
		like: 420000,
		sub: 190000,
		rate: 9.59,
		weekday: ["wed"],
	},
	{
		imgUrl: "./images/unordinary.png",
		title: "unOrdinary",
		author: "uru-chan",
		genre: "superhero",
		info: `Nobody paid much attention to John – just a normal teenager at a high school where the social elite happen to possess unthinkable powers and abilities. But John’s got a secret past that threatens to bring down the school’s whole social order – and much more. Fulfilling his destiny won’t be easy though, because there are battles, frenemies and deadly conspiracies around every corner.`,
		like: 42000000,
		sub: 5000000,
		rate: 9.76,
		weekday: ["thu"],
	},
	{
		imgUrl: "./images/unholyBlood.png",
		title: "Unholy Blood",
		author: "Lina Im / Jeonghyeon Kim",
		genre: "supernatural",
		info: `When vampires destroy her chance to have the normal life she’s always wanted, Hayan is forced to draw on her darkest secret to rid the world of the merciless hunters that took it over 10 years ago. With the support of a rising star in the local police force, Hayan steps up to protect her loved ones, face her past, and get her revenge.`,
		like: 7800000,
		sub: 1300000,
		rate: 9.85,
		weekday: ["thu"],
	},
	{
		imgUrl: "./images/seeYouInMy19thLife.png",
		title: "See You in My 19th Life",
		author: "Lee Hey",
		genre: "romance",
		info: `Jieum Ban has an extraordinary ability: she can remember the memories of all her past lives. After her previous life is cut short by a tragic accident, she sets out to reconnect with the people of her past life in her current one. Will memories of her 18th life sabotage romance in her 19th? Or will love endure across different lives?`,
		like: 3500000,
		sub: 840000,
		rate: 9.89,
		weekday: ["thu"],
	},
	{
		imgUrl: "./images/jungleJuice.png",
		title: "Jungle Juice",
		author: "HYEONG EUN / JUDER",
		genre: "action",
		info: `Suchan Jang is an extraordinary college student at the top of the social food chain. But underneath the perfect facade, he hides a pair of insect wings that suddenly grew when he used a mysterious bug spray called "Jungle Juice.” Suchan's life crumbles when he bares his wings to the world to save someone's life. When all hope seems lost, Suchan stumbles upon a hidden world of insect humans where everyone is accepted for what they are. But the law of the jungle governs this secret society and all must fend for themselves in order to survive.`,
		like: 1300000,
		sub: 560000,
		rate: 9.82,
		weekday: ["thu"],
	},
	{
		imgUrl: "./images/shotgunBoy.png",
		title: "Shotgun Boy",
		author: "Carnby Kim / Hongpil",
		genre: "thriller",
		info: `While running for his life in the woods, bullying victim Gyuhwan stumbles upon a shotgun and just enough shells for his classmates. It’s a recipe for disaster. But fate takes an unexpected turn when he returns to find his classmates under attack by brain-eating creatures. Now, the only thing that stands in the way of their ravenous feast is a boy with a shotgun.`,
		like: 845000,
		sub: 480000,
		rate: 9.86,
		weekday: ["thu"],
	},
	{
		imgUrl: "./images/antiStalker.png",
		title: "AntiSTALKER",
		author: "VOKIVORMOK",
		genre: "romance",
		info: `At this school usual students study with vampires from wealthy families. She is a representative from disciplinary committee, he is a guy who breaks school rules. She is a hunter, he is a target. He is her stalker, she is his target.`,
		like: 2600000,
		sub: 540000,
		rate: 9.72,
		weekday: ["thu"],
	},
	{
		imgUrl: "./images/weakHero.png",
		title: "Weak Hero",
		author: "SEOPASS / RAZEN",
		genre: "action",
		info: `Once the bullies target you, it’s game over. The school is run by tyrants whose favorite hobby is tormenting the weakest kids in class. But then Gray arrived. This mysterious new student threatens to dismantle the established order. He may be small in stature, but his calculative and brutal fighting leaves unsuspecting opponents lying on the floor begging for mercy. Now the school's toughest bullies have to scramble to take down this new and unusual hero.`,
		like: 8500000,
		sub: 970000,
		rate: 9.85,
		weekday: ["thu"],
	},
	{
		imgUrl: "./images/suitorArmor.png",
		title: "Suitor Armor",
		author: "Purpah",
		genre: "fantasy",
		info: `Lady-in-waiting, Lucia believes getting through the royal wedding will be the toughest part of her new life. That is until she finds herself falling head over heels with Modeus, an up-and-coming knight to the king's guard. With her newfound interest, she is quickly awakened to the mysteries of the kingdom when she learns Modeus is in fact an enchanted suit of armor without a soul. Could there be more to him than just shining armor?`,
		like: 3500000,
		sub: 1000000,
		rate: 9.75,
		weekday: ["fri"],
	},
	{
		imgUrl: "./images/iLoveYoo.png",
		title: "I Love Yoo",
		author: "Quimchee",
		genre: "drama",
		info: `Dogged by pain and misfortune from the very beginning, Shin-Ae decides she wants nothing to do with people nor anything to do with romance. Although content with her unsocial, boring, loveless existence, her lifestyle is challenged after she ruins an unsuspecting strangers' clothes.`,
		like: 27000000,
		sub: 4200000,
		rate: 9.78,
		weekday: ["fri"],
	},
	{
		imgUrl: "./images/soIMarriedTheAntiFan.png",
		title: "So I Married the Anti-Fan",
		author: "Jaerim / Eunjeong Kim",
		genre: "romance",
		info: `How far would you go to take down the person you hate most? With no house, no job, and nothing left to lose, Geunyeong Lee is willing to risk it all to bring down the country’s national treasure, Korean superstar Who Joon. But once the two really get to know each other, bringing him down suddenly becomes a lot harder. Will she be able to ruin him once and for all after she learns the truth about the man behind the popstar?`,
		like: 310000,
		sub: 380000,
		rate: 9.53,
		weekday: ["mon","fri"],
	},
	{
		imgUrl: "./images/foreverAfter.png",
		title: "Forever After",
		author: "Hannah Patten / Violet Matter ... ",
		genre: "comedy",
		info: `Robin just wants an easy life. Land a prince, live like a princess; it worked out for Cinderella. Self-respect need not apply. When her wish to live out a real-life fairytale is misinterpreted by the Fates, she finds herself in the storybook realm of Forever After, only she’s not a princess at all! Cast as the Prince, Robin must fight her way through the broken stories of her youth and restore their happy endings if she ever hopes to return home. Some things in Forever After are not quite as they were written, and Robin is not the only one racing through the tales. Stuck with all the responsibility she never wanted, Robin could be the hero to save them all—but not if the Wicked Witch has anything to say about it.`,
		like: 168000,
		sub: 243000,
		rate: 9.18,
		weekday: ["fri"],
	},
	{
		imgUrl: "./images/theGodOfHighSchool_mul.png",
		imgMulUrl: "./images/theGodOfHighSchool_mul.png",
		title: "The God of High School",
		author: "Yongje Park",
		genre: "action",
		info: `Mori Jin is a high school student and Taekwondo specialist who enters "The God of High School," a fighting tournament that promises the winner anything they want. What began as a competition to seek out the best high school fighter soon reveals itself to be part of a much greater plot that goes beyond Mori's wildest imagination. What will he give to become a true god?`,
		like: 23000000,
		sub: 2200000,
		rate: 9.70,
		weekday: ["fri"],
	},
	{
		imgUrl: "./images/midnightPoppyLand.png",
		title: "Midnight Poppy Land",
		author: "Lilydusk",
		genre: "romance",
		info: `After making a grisly discovery in the countryside, a small town book editor’s life gets entangled with a young Mafia lord and his intimidating bodyguard...even as every step she takes draws her deeper into the dangerous underworld of the city.`,
		like: 8500000,
		sub: 1900000,
		rate: 9.82,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/theKissBet.png",
		title: "The Kiss Bet",
		author: "Ingrid Ochoa",
		genre: "romance",
		info: `It’s senior year and Sara Lin just turned 18. She’s got great friends, a cool Dad (or so he thinks) and a whole lot ahead of her. The last thing she needs is to worry about having her first kiss. But that’s all about to change because her good pal Patrick just challenged her to a bet that will either lead to love, heartbreak or embarrassment…or maybe all three.`,
		like: 6600000,
		sub: 1100000,
		rate: 9.69,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/menOfTheHarem.png",
		title: "Men of the Harem",
		author: "HereLee / Alphatart ... ",
		genre: "fantasy",
		info: `Scorned by her lover and thrown into power after the mysterious assassination of her father, Latil must marry to secure her sovereignty of Tarium. Instead of choosing one man to become her Royal Consort, she chooses five young men from all walks of life to join her Harem. Will Latil ever solve her father’s murder, and can she keep the peace in her Harem?`,
		like: 2400000,
		sub: 8700000,
		rate: 9.73,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/likeWindOnADryBranch_mul.png",
		imgMulUrl: "./images/likeWindOnADryBranch_mul.png",
		title: "Like Wind on a Dry Branch",
		author: "Dalsaeowl / Hwaeum",
		genre: "fantasy",
		info: `As plague and turmoil afflicts the empire, enchanting widow Rieta Tristi finds herself at the mercy of a malicious nobleman and his dying wish to have her buried alive beside his corpse. The plague has taken her husband, slave traders have taken her young child, and now her own life is at risk -- until an unexpected visit from the empire's outcast prince changes everything.`,
		like: 2100000,
		sub: 850000,
		rate: 9.78,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/hisMajestysProposal.png",
		title: "His Majesty's Proposal",
		author: "Yeyeong / Studio Inus ...",
		genre: "fantasy",
		info: `A broken engagement and one too many drinks are the catalysts for a mistake that will change Penelope Zecalion’s life forever, as she finds herself waking up in bed with the emperor! Grouchy, foul-mouthed Penelope is reluctant to let the emperor into her heart after her first engagement went so wrong. Can the emperor change her mind and win her heart?`,
		like: 350000,
		sub: 390000,
		rate: 8.85,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/shesHopless.png",
		title: "She's Hopeless",
		author: "Seokwoo",
		genre: "drama",
		info: `Though she comes from a rich family, Gabin is a bullied loner at school. That doesn't mean she puts up with bullying from other students, though -- Gabin is infamous for her fierce personality. Worried about Gabin's well-being, her family secretly offers Tae-ung $500,000 to transfer schools and act as her bodyguard. Will Tae-ung be able to protect her from the school bullies, all while keeping his identity hidden from Gabin and the other students?`,
		like: 320000,
		sub: 372000,
		rate: 9.80,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/yourThrone.png",
		title: "Your Throne",
		author: "SAM",
		genre: "fantasy",
		info: `Tensions are brewing under the seemingly calm surface of the Vasilios Empire, a kingdom ruled by the Imperial Family and the Temple. Lady Medea Solon has lost her place next to Crown Prince Eros, but resolves to do whatever it will take to win back what's rightfully hers. Will she reclaim her throne?`,
		like: 6600000,
		sub: 1100000,
		rate: 9.81,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/theStrongestFlorist.png",
		title: "The Strongest Florist",
		author: "Hyun hoo Joo / Kumtata",
		genre: "action",
		info: `Even though he’s built like a fighter with a fearsome scowl, Jaeho would love nothing more than to become a florist instead. Unfortunately, Jaeho’s overbearing father disapproves, pushing his son to become an MMA fighter instead. Jaeho enters the virtual reality game, New World, to escape his father’s ambitions, but will he be able to realize his dreams?`,
		like: 1000000,
		sub: 385000,
		rate: 9.86,
		weekday: ["sat"],
	},
	{
		imgUrl: "./images/loreOlympus.png",
		title: "Lore Olympus",
		author: "Rachel Smythe",
		genre: "romance",
		info: `Witness what the gods do…after dark. The friendships and the lies, the gossip and the wild parties, and of course, forbidden love. Because it turns out, the gods aren’t so different from us after all, especially when it comes to their problems. Stylish and immersive, this is one of mythology’s greatest stories -- The Taking of Persephone -- as it’s never been told before.`,
		like: 38000000,
		sub: 5000000,
		rate: 9.73,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/theRemarriedEmpress.png",
		title: "The Remarried Empress",
		author: "Alphatart / Sumpul",
		genre: "fantasy",
		info: `Navier Ellie Trovi was an empress perfect in every way -- intelligent, courageous, and socially adept. She was kind to her subjects and devoted to her husband. Navier was perfectly content to live the rest of her days as the wise empress of the Eastern Empire. That is, until her husband brought home a mistress and demanded a divorce. “I accept this divorce… And I request an approval of my remarriage.” In a shocking twist, Navier remarries another emperor and retains her title and childhood dream as empress. But just how did everything unfold?`,
		like: 12000000,
		sub: 1600000,
		rate: 9.87,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/myGentlyRaisedBeast_mul.png",
		imgMulUrl: "./images/myGentlyRaisedBeast_mul.png",
		title: "My Gently Raised Beast",
		author: "Yeoseulki / Early Flower ...",
		genre: "romance",
		info: `Blondina is living a real-life Cinderella story. After growing up poor and enduring a difficult childhood, she discovers that she is a princess of the Ates empire. However, her estranged father and half-siblings give her the cold shoulder when she moves into the palace, and Blondina must keep a low profile. That all changes when she befriends Amon, a cat-like creature with mysterious intentions. For years, creatures like Amon and humans have struggled to live in harmony. Can Blondina and Amon’s friendship bring peace, or will it deepen the rift between their people?`,
		like: 890000,
		sub: 616000,
		rate: 9.85,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/castleSwimmer.png",
		title: "Castle Swimmer",
		author: "Wendy Lian Martin",
		genre: "fantasy",
		info: `What happens when your entire life is ruled by a prophecy – your future foretold by people you’ve never met, who died long before you were born. Such is the story of two young sea creatures. One believed to be a guiding light for his people, a Beacon who will lead them to a bright, prosperous future. The other is a teenage prince for who’s destiny is to KILL the Beacon so that HIS own people might thrive. When both reject the course set for them, it leads to a raucous adventure as big and unpredictable as the ocean itself – and a romance that nobody could have predicted.`,
		like: 13200000,
		sub: 2100000,
		rate: 9.84,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/lumine.png",
		title: "LUMINE",
		author: "Emma Krogell",
		genre: "fantasy",
		info: `A runaway werewolf, Lumine, meets a witch boy named Kody and is being hired to work as his bodyguard. Lumine, being determined to befriend Kody, tries everything to get Kody to trust him, while Kody tries to keep Lumine away from him. Their life gets even more complicated after an unfortunate event that leaves them to try to survive on their own.`,
		like: 17000000,
		sub: 2900000,
		rate: 9.83,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/bladesOfFurry.png",
		title: "Blades of Furry",
		author: "Deya Muniz / Emily Erdos",
		genre: "romance",
		info: `Emile is an up-and-coming skater in the beloved sport of Skate Battles, a high-stakes combo of figure skating and martial arts. Radu is a well-known senior skater and several time champ with the world at his feet. However, during an ill-fated match between the two, Emile discovers Radu's secret, which could threaten to destroy him. Will Emile keep his secret? Or could this rivalry turn into something more...?`,
		like: 1200000,
		sub: 360000,
		rate: 9.61,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/imTheGrimReaper.png",
		title: "I'm the Grim Reaper",
		author: "GRAVEWEAVER ",
		genre: "supernatural",
		info: `On earth there are bad people, and then there are REALLY BAD people. If you’re one of the latter, you don’t just get sent to Hell, you get sent to Hell and get assigned a job collecting the souls of some of the worst people on Earth. Such is the career path of a young woman named Scarlet, who dies and is delivered down to the fiery underworld only to find herself in an entry level position as…The Grim Reaper!`,
		like: 6800000,
		sub: 1400000,
		rate: 9.80,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/jacksonsDiary.png",
		title: "Jackson's Diary",
		author: "Paola Batalla",
		genre: "supernatural",
		info: `The year is 1989, and Jackson is starting his senior year at a brand new school. Even though he's back in his hometown with his new family, he can't seem to shake this ominous and uneasy feeling invading his mind. It's not until he meets the popular kid, Exer, that reality starts to feel more like the work of his imagination.`,
		like: 1800000,
		sub: 561000,
		rate: 9.65,
		weekday: ["sun"],
	},
	{
		imgUrl: "./images/theNewlywedDiaryOfAWitchAndADragon.png",
		title: "The Newlywed Diary of a Witch and a Dragon",
		author: "New lung / Dimang ... ",
		genre: "romance",
		info: `After spending the night with a recent hire of the Tower of Magic, Wendy Blanchett, a talented young leader of the Rune Research Division, is faced with an impossible dilemma. She fears for her position and reputation when the newbie, Aiden Winters, asks her to marry him. Unbeknownst to Wendy, Aiden seems to have secrets of his own. Will their love blossom, or will his secrets tear them apart?`,
		like: 1500000,
		sub: 647000,
		rate: 9.35,
		weekday: ["sun"],
	},
]	